all: marcosOndruska marcosOndruskaRecursive

marcosOndruska: marcosOndruska.o 
	cc -o marcosOndruska marcosOndruska.c 	

marcosOndruskaRecursive: marcosOndruskaRecursive.o 
	cc -o marcosOndruskaRecursive marcosOndruskaRecursive.c 

clean:
	rm *.marcosOndruska